### ISSUE TITLE
drop in replacement for conv1D?

### ISSUE THREAD

**Issue by listener17** [thjashin/multires-conv#4]
Thanks for sharing this interesting work!
Can the MultiresConv be utilized as a drop-in replacement for conv1d operating on audio signals? 

Also, is it possible to build an inverse or transpose MultiresConv and use it as a drop-in replacement for transposed conv1d?

**Comment by thjashin** [comment]
Thanks for your interest! Short answer to the first question: Yes. Think of it as a general sequence-to-sequence mapping. The inverse MultiresConv idea is interesting. I haven't thought about it deeply but it looks plausible.

**Comment by listener17** [comment]
Thanks @thjashin

**Comment by listener17** [comment]
@thjashin: if I would like to replace the regular conv1d layer in my model with your multires layer, how should I call your layer?
